-- A.T.L.A.S Window Manager visual polish
-- Generated by Hermes from approved PRD. User-owned override, safe to remove/rollback.

hl.config({
  general = {
    gaps_in = 5,
    gaps_out = 10,
    border_size = 3,
    resize_on_border = true,
    extend_border_grab_area = 14,
    hover_icon_on_border = true,
    col = {
      active_border = { colors = { "rgba(a8ecffee)", "rgba(35c4ffee)", "rgba(1478e6dd)" }, angle = 45 },
      inactive_border = { colors = { "rgba(0a2a4a99)", "rgba(07304088)" }, angle = 45 },
      nogroup_border_active = { colors = { "rgba(a8ecffee)", "rgba(35c4ffee)" }, angle = 45 },
      nogroup_border = "rgba(07304088)",
    },
    snap = {
      enabled = true,
      window_gap = 12,
      monitor_gap = 12,
      border_overlap = true,
      respect_gaps = true,
    },
  },
  decoration = {
    rounding = 12,
    rounding_power = 2,
    active_opacity = 1.0,
    inactive_opacity = 0.96,
    fullscreen_opacity = 1.0,
    shadow = {
      enabled = true,
      range = 18,
      render_power = 3,
      color = "rgba(00f5ff30)",
      color_inactive = "rgba(00182030)",
    },
  },
  animations = {
    enabled = true,
  },
})

-- Keep true fullscreen clean for video/games/presentations.
-- Maximized/tiled windows keep the subtle A.T.L.A.S focus border.
hl.window_rule({ match = { fullscreen = 1 }, border_size = 0, rounding = 0 })

-- Hardware cursors ON (2026-10-08): after the Oct 8 update (new Hyprland/mesa) forced software cursors
-- rendered NOTHING on this Intel GPU, so the pointer was invisible. If duplicate/ghost cursors return on
-- dock displays, try `no_hardware_cursors = 2` (auto) rather than true.
hl.config({
  cursor = {
    no_hardware_cursors = false,
  },
})

-- Opt another application in to Omarchy's standard transparency.
-- Find its class with: hyprctl clients
-- o.transparent_window("my-app")
-- o.transparent_window("my-app", "0.9 0.85") -- Custom active/inactive opacity.
